// Single source of truth for WEB_* tab names/headers — used by both the
// bootstrap script and every repository, so column order can never drift
// between "what bootstrap created" and "what a repository writes".

export const CMS_TABS = {
  bdsOverrides: "WEB_BDS_OVERRIDES",
  bdsCustom: "WEB_BDS_CUSTOM",
  projects: "WEB_PROJECTS",
  news: "WEB_NEWS",
  contacts: "WEB_CONTACTS",
  media: "WEB_MEDIA",
  settings: "WEB_SETTINGS",
  pageContent: "WEB_PAGE_CONTENT",
  adminSecurity: "WEB_ADMIN_SECURITY",
} as const;

export const CMS_HEADERS: Record<(typeof CMS_TABS)[keyof typeof CMS_TABS], string[]> = {
  [CMS_TABS.bdsOverrides]: ["source_id", "patch_json", "hidden", "updated_at", "updated_by"],
  [CMS_TABS.bdsCustom]: [
    "id",
    "slug",
    "room_no",
    "location",
    "address",
    "price",
    "service_fee",
    "area",
    "vertical_access",
    "property_type",
    "description",
    "highlights_json",
    "availability",
    "bedroom_count",
    "furnishing_status",
    "media_json",
    "commission",
    "guide_person",
    "internal_notes",
    "published",
    "created_at",
    "updated_at",
  ],
  [CMS_TABS.projects]: [
    "id",
    "slug",
    "name",
    "location",
    "investor",
    "status",
    "summary",
    "amenities_json",
    "progress_text",
    "progress_percent",
    "media_json",
    "published",
    "created_at",
    "updated_at",
    "progress_photos_json",
    "unit_types_json",
    "property_type",
    "scale",
    "unit_count",
    "highlights_json",
    "map_query",
    "masterplan_image",
    "show_masterplan",
    "apartment_area",
    "legal_status",
  ],
  [CMS_TABS.news]: [
    "id",
    "slug",
    "title",
    "category",
    "status",
    "published_at",
    "read_minutes",
    "excerpt",
    "cover_media_id",
    "sections_json",
    "published",
    "created_at",
    "updated_at",
  ],
  [CMS_TABS.contacts]: ["id", "created_at", "name", "phone", "need", "area", "message", "status", "ip_hash"],
  [CMS_TABS.media]: [
    "id",
    "drive_file_id",
    "filename",
    "mime_type",
    "size_bytes",
    "web_view_link",
    "uploaded_by",
    "created_at",
  ],
  // Single-row tab: row 2 holds the whole record. Company contact details
  // that used to be hardcoded in three separate components.
  [CMS_TABS.settings]: [
    "address",
    "map_query",
    "phone_primary",
    "phone_secondary",
    "email",
    "hours_weekday",
    "hours_weekend",
    "updated_at",
    "profile_pdf_url",
  ],
  // One row per editable public page. Structured repeating blocks live in
  // JSON so adding a stat/value/card never shifts unrelated CMS columns.
  [CMS_TABS.pageContent]: ["page_key", "content_json", "updated_at"],
  // Single-row, server-only record. The TOTP seed is encrypted with
  // AUTH_SECRET before it reaches Sheets; passwords remain scrypt hashes.
  [CMS_TABS.adminSecurity]: [
    "password_hash",
    "totp_secret_ciphertext",
    "totp_enabled",
    "updated_at",
  ],
};
